# Generated by Django 4.1.2 on 2022-10-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('td', models.CharField(max_length=50)),
                ('td_description', models.CharField(max_length=600)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
